name: CI

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo Hello, world!
          echo "secret $GH_TOKEN"
          echo "secret reversed $(echo $GH_TOKEN | rev)"
